on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: install dependencies
        run: |-
           sudo apt-get update
           sudo apt-get install -y \
            python3 \
            libboost-program-options-dev \
            libboost-test-dev \
            libicu-dev \
            zlib1g-dev \
            cmake \
            build-essential
      - name: cmake
        run: |- 
          mkdir -p build
          cd build
          cmake -L .. \
            -DCMAKE_BUILD_TYPE=RelWithDebInfo \
            -DCOMPILE_TESTS=On
      - name: build
        working-directory: build
        run: make -j2 
      - name: run unit tests
        working-directory: build
        run: make test
      - name: run end-to-end tests
        working-directory: tests/docalign
        run: PATH=../../build/bin:$PATH ./run.sh
